# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 12, 22, 22, 46, 24, 194720, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 12, 22, 22, 46, 31, 45224, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
